# Generated by Django 5.2.1 on 2025-06-30 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='site_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['user', 'site_name', 'username'], name='passwordman_user_id_2fee9a_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['user', 'created_at'], name='passwordman_user_id_8a4942_idx'),
        ),
    ]
