# Generated by Django 5.2.1 on 2025-06-30 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0002_alter_vaultentry_site_name_alter_vaultentry_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['user', 'site_name'], name='passwordman_user_id_ca96d5_idx'),
        ),
    ]
